# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - prettier
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
env:
  # TODO: find out how to turn this on only for src/**/*.test.js files
  jest: true
rules:
  prettier/prettier: "error"
  '@typescript-eslint/no-explicit-any': 'off'
